### ISSUE TITLE
Position Utility classes need example usage

### ISSUE THREAD

**Issue by lukehutch** [uikit/uikit-site#4]
The Position Utility classes need to describe how to specify the relative or absolute coordinates:

https://github.com/uikit/uikit-site/blob/develop/docs/pages/position.md

**Comment by philoest** [comment]
The classes are only for the case where you need to set this specific css attribute, the coordinates always needs to be set via custom CSS code. That was one of the reasons we didn't add a example for this, since these will only be used in very specific use cases where none of the classes above can be used...
